### ISSUE TITLE
NadekoUpdater does not work

### ISSUE THREAD

**Issue by boredgamerz** [Kwoth/NadekoUpdater#5]
http://puu.sh/rs6VA/698e2f0c44.png <-- screenshot

I start it, then it crashes instantly

**Comment by boredgamerz** [comment]
Works to just use the launcher ^_^

**Comment by Kwoth** [comment]
run it as administrator.

**Comment by boredgamerz** [comment]
Tried to run it as admin, same result. I tried to use the .exe manually. the latest stable release did not download but the latest did work.
